# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
